config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # devise_for :user do
  #   get "/dashboard", to: "devise/sessions#dashboard"
  # end
  root to: 'pages#home'
  resources :flats  do
    resources :bookings, only: [:new, :create, :show, :index, :destroy]
    resources :reviews, only: [:new, :create, :update, :show, :edit, :index]
  end


  get "/dashboard", to: "pages#dashboard"
  #cresources :users, only: [:show]

  resources :reviews, only: [ :destroy ]
  # resources :bookings, only: [ :destroy ]
end
# heroku pg:reset
# heroku run rails db:migrate
# heroku run rails db:seed

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flat
  belongs_to :user

  has_many :reviews

  def datepicker_input form, field
    content_tag :td, :data => {:provide => 'datepicker', 'date-format' => 'yyyy-mm-dd', 'date-autoclose' => 'true'} do
      form.text_field field, class: 'form-control', placeholder: 'YYYY-MM-DD'
    end
  end

  validates :move_in_date, presence: true
  validates :move_out_date, presence: true

  # def all_bookings_for_user
  #   self.bookings.map do |booking|
  #   booking.review
  #   end
  # end
  # validates :status, inclusion: { in: ['requested by guest', 'confirmed by host', 'cancelled by guest', 'denied by host', 'paid']}
end

app/models/flat.rb
class Flat < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_many :reviews

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?


  def average_rating
    sum = 0
    # reviews = all_reviews_for_flat
    reviews = self.reviews
    return 0 if reviews == []
    reviews.each do |review|
      sum += review.stars unless review.nil?
    end
    sum / reviews.size
  end

  def sum_rating
    reviews = self.reviews
    reviews.count
  end

  # has_many :reviews, through: :bookings
  mount_uploader :photo, PhotoUploader

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking, optional: true
  belongs_to :flat


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :flats
  has_many :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
  include Pundit

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :destroy]

  def index
    @bookings = policy_scope(Booking).where(params[:id])
    @bookings = Booking.all
    @flat = Flat.find(params[:flat_id])
  end

  def show
    @flat = Flat.find(params[:flat_id])
    authorize @booking
  end

  def new
    @booking = Booking.new
    @user = current_user
    @flat = Flat.find(params[:flat_id])
    authorize @booking
  end

  def create
    @flat = Flat.find(params[:flat_id])
    @booking = Booking.new(booking_params)
    authorize @booking
    @booking.flat = @flat
    @booking.user = current_user
    if @booking.save
      redirect_to flat_booking_path(@flat, @booking)
    else
      render :new
    end
  end

  def destroy
    authorize @booking
    # raise
    @flat = @booking.flat
    @booking.destroy
    redirect_to flat_path(@flat), notice: 'booking was successfully deleted.'
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:move_in_date, :move_out_date, :flat_id)
  end

end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: [:show, :edit, :destroy, :update]

  def index
    # @flats = Flat.all
      @flats = policy_scope(Flat).order(created_at: :desc).where.not(latitude: nil, longitude: nil)
    if params[:query].present?

      # @flats = @flats.where(address: params[:query])
      sql_query = " \
        flats.title @@ :query \
        OR flats.address @@ :query \
        OR flats.city @@ :query \
        "
      # sql_query = "title ILIKE :query OR address ILIKE :query"
      @flats = @flats.where(sql_query, query: "%#{params[:query]}%")
    end
    # authorize @flats
    # @flats = Flat.where.not(latitude: nil, longitude: nil)

    @markers = @flats.map do |flat|
      {
        lat: flat.latitude,
        lng: flat.longitude,
        infoWindow: render_to_string(partial: "infowindow", locals: { flat: flat }),
        image_url: helpers.asset_url('https://i.ibb.co/wcBGNNd/Marker.png')
      }
    end
  end

  def show
    @stars_avg = compute_stars_avg
    @booking = Booking.new
    @user = current_user
    @flat = Flat.find(params[:id])
    authorize @flat
    authorize @booking
  end

  def new
    @flat = Flat.new
    @user = current_user
    authorize @flat
  end

  def create
    @flat = Flat.new(flat_params)
    authorize @flat

    @flat.user = current_user

    if @flat.save!
      redirect_to flat_path(@flat)
    else
      render :new
    end
  end

  def edit
    authorize @flat
  end

  def update
    authorize @flat
    if @flat.update(flat_params)
      redirect_to @flat, notice: 'Flat has been successfully updated'
    else
      render :edit
    end
  end

  def destroy
    authorize @flat
    @flat.destroy
    redirect_to dashboard_path, notice: 'flat was successfully deleted.'
  end

  private

  def compute_stars_avg
    stars = []
    @flat.reviews.each do |review|
      stars << review.stars
    end
    stars_sum = stars.reduce(0) { |sum, num| sum + num }
    stars_sum.to_f / stars.count
  end

  def set_flat
    @flat = Flat.find(params[:id])
  end

  def flat_params
    params.require(:flat).permit(:address, :title, :city, :description, :price_per_night, :photo, :photo_cache)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # skip_before_action :authenticate_user!, only: :home
  def home
  end

  def dashboard
    @user = current_user
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!, :set_review, only: [:show, :show, :destroy, :update, :edit]

  def index
    # @booking = Booking.find(params[:booking_id])
    @flat = Flat.where(params[:flat_id])
    @reviews = policy_scope(Review).where(flat_id: (params[:flat_id]))
    # @reviews = policy_scope(Review).where(booking_id: @booking.id)
  end

  def show
    @flat = Flat.find(params[:flat_id])
    authorize @review
  end

  def new
    @review = Review.new
    authorize @review
    @flat = Flat.find(params[:flat_id])
  end

  def create
    @flat = Flat.find(params[:flat_id])
    @review = Review.new(review_params)
    authorize @review
    @review.flat = @flat
    if @review.save!
      redirect_to flat_reviews_path(@flat)
    else
      render :new
    end
  end

  def update
    authorize @review
    if @review.update(review_params)
      redirect_to flat_review_path(@flat, @review), notice: 'review has been successfully updated'
    else
      render :edit
    end
  end

  def destroy
    authorize @review
    @flat = @review.flat
    @review.destroy
    redirect_to flat_path(@flat), notice: 'review was successfully deleted.'
  end

  private

  def set_review
    @review = Review.find(params[:id])
  end

  def review_params
    params.require(:review).permit(:description, :stars)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<%= simple_form_for([@flat, @booking]) do |f| %>
    <div>
      <div class="form-inline input-form">
        <%= f.input :move_in_date, label: 'Start', as: :string,   input_html: { id:"start_date", class: "input-fields"} %>
        <%= f.input :move_out_date, label: 'End', as: :string,  input_html: { id:"end_date", class: "input-fields"}%>
      </div>
      <br>
      <%= f.submit class: "btn-book text-alignment", id: "  book" %>
      <% end %>
</div>

app/views/bookings/index.html.erb
<ul>
  <% @flat.bookings.each do |b| %>
      <% b.reviews.each do |r|%>
    <li>
      <%= r.description %>
      <%= r.stars %>
    </li>
    <% end %>
  <% end %>
</ul>

app/views/bookings/new.html.erb
<div class="list-margin">
  <h1 style="padding-left: 20px;"><strong>Confirm your booking</strong></h1>
  <div class="display-index">
    <div class="card-trip">
      <%= cl_image_tag @flat.photo %>
      <div class="card-trip-infos">
        <div>
          <h2><%= @flat.title %></h2>
          <p><%= @flat.description %></p>
          <br>
        </div>
        <h2 class="card-trip-pricing"><%= @flat.price_per_night %> €</h2>
      </div>
    </div>
    <div class="card-trip p-4 ml-4">
        <h1><strong>Your Booking in <%= @flat.city %></strong></h1>
        <br>
        <%= render 'form', booking: @booking %>
    </div>
  </div>
</div>

app/views/bookings/show.html.erb
<body  style="background-image: linear-gradient(rgba(0,0,0,0.5),rgba(0,0,0,0.5)),  url('https://ui-ex.com/images/texas-drawing-skyline-2.png')">

  <div class="container">
    <h1>Your Booking in <%= @flat.city %></h1>
      <p class="move">Start date: <%= @booking.move_in_date.strftime("%A, %d %b %Y") %></p>
      <p class="move">End date: <%= @booking.move_out_date.strftime("%A, %d %b %Y") %></p>
      <% duration = @booking.move_out_date - @booking.move_in_date %>
      <p class="move">Length: <%= duration.to_i %> days</p>
      <% costs = duration.to_i * @flat.price_per_night %>
      <p class="move">Total costs: <%= costs.to_i%> EUR</p>

    <div class="flexbox">

      <%= link_to "Delete Booking", flat_booking_path(@flat, @booking), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn ", id: "couple"  %>
      <%= link_to "See Reviews", flat_reviews_path(@flat, @review), class: "btn ", id: "couple" %>
      <%= link_to "Write a Review", new_flat_review_path(@flat, @booking), class: "btn ", id: "couple" %>
      <%= link_to "Back", flat_path(@flat), class: "btn ", id: "couple"  %>
    </div>
  </div>
</body>

app/views/dashboard/_bookings.html.erb
<div class="list-margin">

  <div class="dashboard">
    <% if @current_user.bookings.count.nil? %>
        <p>Looks like you haven't planned any trip. Time to get some inspiration.</p>
      <% else %>
      <br>
      <%= render 'dashboard/bookingsdashboard' %>
        <% end %><br>
    <span id="button-red"><%= link_to "Plan your next trip", flats_path %></span>
    <br><br><br><br><br>
  </div>

</div>

app/views/dashboard/_bookingsdashboard.html.erb
  <h1>Your upcoming Trips</h1>
  <div class="row">
    <% @user.bookings.each do |booking| %>
      <div class="col-md-4">
      <div class="card-flat-dashboard m-2">
        <%= cl_image_tag booking.flat.photo %>
          <div class="card-flat-dashboard-infos">
            <div id="card-dashboard-rating">
              <h2><%= link_to booking.flat.title, booking.flat %></h2>
              <p>Booked from <%= booking.move_in_date %> until <%= booking.move_out_date %></p>
              <p><%= link_to " View details",flat_booking_path(booking.flat,booking)%></p>
            </div>
          </div>
          </div>
      </div>
      <% end %>
  </div>

app/views/dashboard/_carddashboard.html.erb
<div class="row">
  <% @user.flats.each do |flat| %>
  <div class="col-md-4">
    <%= link_to flat_path(flat) do %>
    <div class="row d-inline">
      <div class="card-flat-dashboard my-4">
        <%= cl_image_tag flat.photo, class: "card-flat-dashboard-img" %>
        <div class="card-flat-dashboard-infos">
          <div id="card-dashboard-rating">
           <!--  <p><%#= link_to flat.city.upcase, flat_path(flat) %></p> -->
           <h2><%#= link_to flat.title, flat %></h2>
           <h2><%= flat.title %></h2>
           <%#= raise %>
           <% flat.average_rating.times do %>
           <i class="fas fa-star"></i>
           <% end %> <%if flat.sum_rating == 0 %>
           <p><em>No ratings yet</em></p>
           <% else%> <%=  flat.sum_rating  %>
           <% end  %>
           <p><%= link_to " Delete ", flat_path(flat), method: :delete, data: { confirm: 'are you sure?'}  %> | <%= link_to "  Edit " , edit_flat_path(flat) %> </p>
         </div>
       </div>
     </div>
   </div>
   <% end %>
 </div>
 <% end %>
</div>

app/views/dashboard/_flats.html.erb
<div class="list-margin">

  <div class="dashboard">
    <% if @user.flats == []  %>
    <h3 style="text-align:left;">Become a host</h3><br>
    <p>Your place is a place to stay? Share your home with others.</p><br>
    <span id="button-red"><%= link_to "Become a host", new_flat_path %></span>
    <% else  %>

    <% if @user.flats.count == 1  %>
    <h3 style="text-align:left;">Your flat</h3>
    <p>This is the home you currently offer to others.</p>
    <% else %>
    <h3 style="text-align:left;">Your flats</h3>
    <p>Here's an overview of all your flats.</p>
    <% end %>
    <%= render 'dashboard/carddashboard' %>

    <br><br><span id="button-red"><%= link_to "Add another home", new_flat_path %></span>
    <% end %>
    <br><br>
  </div>

</div>

app/views/dashboard/_overview.html.erb
<div class="list-margin">
    <div class="dashboard" >
      <h3 style="text-align:left;">Welcome back, <%= @user.first_name %>.</h3><br>
      <p>Your activities:</p>
      <table style="width:100%">
        <tr>
          <th><i class="fas fa-home"></i></th>
          <td>
            <% if @user.flats.count == 0  %>
            <p>You currently don't offer any homes to stay. Do you want to become a host? <%= link_to "Click here to become a host.", new_flat_path %></p>
            <% else %>
            <p>You currently offer <%= pluralize @user.flats.size, "flat" %>. </p>
            <% end %>
          </td>
        </tr>
        <tr>
          <th><i class="fas fa-suitcase"></i></th>
          <td>
            <% if @current_user.bookings.nil?  %>
            <p><%= link_to "Time to plan your next trip.", root_path %></p>
            <% else %>
            <p>You have <%= @current_user.bookings.count %> upcoming trips.</p>
            <% end %></td>
          </tr>
        </table>
      </div>
    </div>

app/views/dashboard/_profile.html.erb
<div class="list-margin">

  <div class="dashboard">
    <h3 style="text-align:left;">Update your profile</h3><br>
    <table style="width:100%">
      <tr>
        <td><h4 style="text-align:left;">First Name</h4></td>
        <td style="padding-left:15px;"><%= current_user.first_name %></td>
      </tr>
      <tr>
        <td><h4 style="text-align:left;">Last Name</h4></td>
        <td style="padding-left:15px;"><%= current_user.last_name %></td>
        </tr>
        <tr>
        <td><h4 style="text-align:left;">Email</h4></td>
        <td style="padding-left:15px;"><%= current_user.email %></td>
        </tr>
      </table><br><br>
      <div>
        <span id="button-red"><%= link_to "Update your profile", edit_user_registration_path(@user)  %></span>
      </div>
      <br><br><br>

    </div>

  </div>

app/views/flats/_book-form.html.erb
<div class="form-inline input-form">
  <%= simple_form_for([@flat, @booking]) do |f| %>
    <%= f.input :move_in_date, label: 'Start', as: :string,   input_html: { id:"start_date", class: "input-fields"} %>
    <%= f.input :move_out_date, label: 'End', as: :string,  input_html: { id:"end_date", class: "input-fields"}%>
    <br>
    <%= f.submit class: "btn-book text-alignment", id: "  book" %>
    <% end %>
</div>

app/views/flats/_form.html.erb
<%= simple_form_for([@flat]) do |f| %>
    <%= f.input :title %>
    <%= f.input :city %>
    <%= f.input :address %>
    <%= f.input :description %>
    <%= f.input :price_per_night %>
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden  %>
    <%= f.submit class: 'btn btn-primary my-4' %>
<% end %>

app/views/flats/_infowindow.html.erb
<%= flat.title %>

app/views/flats/_show.html.erb
<div class="card-trip p-4 ml-4 col-md-6">
  <%= cl_image_tag @flat.photo %>
  <div class="card-trip-infos">
    <h2><%= @flat.title %></h2>
    <p><%= @flat.description %></p>
    <%= link_to "See Reviews", flat_reviews_path(@flat, @review), class: "btn ", id: "couple" %>
    <% @flat.average_rating.times do %>
    <i class="fas fa-star"></i>
    <% end %> <%if @flat.sum_rating == 0 %>
    <p><em>No ratings yet</em></p>
    <% else%> <%=  @flat.sum_rating  %>
    <% end  %>
    <br>
  </div>
  <h2 class="card-trip-pricing"><%= @flat.price_per_night %> €</h2>

  <div class="btn btn-book">
    <% if @flat.user == current_user %>
      <%= link_to "Edit this flat", edit_flat_path(@flat) %>
    <% end %>
  </div>
</div>

app/views/flats/edit.html.erb
<div class="list-margin">
  <h1>Edit your flat!</h1>
  <%= render 'form', flat: @flat %>
  <div id="button">
    <%= link_to "back", root_path %>
  </div>
</div>

app/views/flats/index.html.erb
  <div class="list-margin">
    <h1 style="padding-left: 20px; text-align:left; margin-bottom: 10px;">Accomodations</h1>
    <p style="padding-left: 20px;">Explore cities you never want to leave.</p>
    <div class="display-index">
      <%= render 'shared/card' %>
      <div
      id="map"
      style="width: 50%;"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
      ></div>
    </div>
  </div>

app/views/flats/new.html.erb
<div class="list-margin">
  <h1>List your flat!</h1>
  <%= render 'form', flat: @flat %>
  <div class='btn btn-primary'>
    <%= link_to "back", root_path %>
  </div>
</div>

app/views/flats/show.html.erb
<div class="list-margin">
  <h1 style="padding-left: 20px;">Your selected appartment</h1>
  <div class="show-index">

    <div class="col-md-7">
      <div class="card-trip">
        <%= cl_image_tag @flat.photo %>
        <div class="card-trip-infos">
          <div>
            <h2><%= @flat.title %></h2>
            <p><%= @flat.description %></p>
            <%= link_to "See Reviews", flat_reviews_path(@flat, @review), class: "btn ", id: "couple" %>
            <% @flat.average_rating.times do %>
            <i class="fas fa-star"></i>
            <% end %> <%if @flat.sum_rating == 0 %>
            <p><em>No ratings yet</em></p>
            <% else%> <%=  @flat.sum_rating  %>
            <% end  %>
            <br>
          </div>
          <h2 class="card-trip-pricing"><%= @flat.price_per_night %> €</h2>
        </div>
        <div >
          <% if @flat.user == current_user %>
          <span class="btn btn-book"><%= link_to "Edit this flat", edit_flat_path(@flat) %></span>
          <% end %>
        </div>
      </div>

    </div>

    <div class="col-md-5">
      <div class="card-trip p-4 ml-4">
        <h3 style="text-align:center;">Book your flat in <%= @flat.city %></h3>
        <br>
        <%= render 'book-form', booking: @booking %>
      </div>
    </div>

  </div>
</div>

app/views/layouts/_search_form.html.erb
<%= simple_form_for(@flat) do |r| %>
  <%=  r.input :city %>
  <%=  r.submit "Search", class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>CLUBNB</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link href="https://fonts.googleapis.com/css?family=Exo|Roboto&display=swap" rel="stylesheet">
    <link href='https://api.tiles.mapbox.com/mapbox-gl-js/v0.54.0/mapbox-gl.css' rel='stylesheet' />
    <%#= stylesheet_pack_tag 'application', media: 'all' %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %>
  </head>
  <body>

    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <div style="min-height:100vh;"><%= yield %></div>

    <%= render 'shared/footer' %>

        <%= javascript_include_tag 'application' %>
        <%= javascript_pack_tag 'application' %>

  </body>
</html>

app/views/pages/home.html.erb
  <div class="bg-img">
<div class="list-margin">

  <!-- <div class="row"> -->
    <div class="col-md-4">
      <div style="display: flex;align-items: center;justify-content: space-around; height: 100%; width: 100%">
        <div class="box" style="width: 100%">
          <h3>Find a home away from home.</h3>
          <p>Find beautiful apartments around the world because you belong anywhere.</p>
          <p> Be free and travel the world.</p>
          <%= form_tag flats_path, method: :get do %>
          <%= text_field_tag :query,
          params[:query],
          class: "form-control",
            placeholder: "Find a Flat"
            %>
            <%= submit_tag("Search", id:"button", style:"margin-top: 20px") %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="list-margin">
  <h2 style="text-align:center;">Your advantages</h4>
    <div id="home-icons">
      <div class="col-md-4">
        <img src="https://i.ibb.co/Dt0KxSb/noun-house-specification-2368079.png" alt="Wide Selection">
        <h4>Wide Selection</h4>
        <p>Find your kind of property. Single rooms, apartments or houseboats. You name it.</p>
      </div>
      <div class="col-md-4">
        <!-- <img src="https://i.ibb.co/FHBZwRy/noun-Couple-1371841.png" alt="Belong anywhere"> -->
        <img src="https://i.ibb.co/2s8BV3j/noun-Couple-1371841.png" alt="Belong anywhere">
        <h4>Belong anywhere</h4>
        <p>Feel at home, anywhere you go in the world. Never worry about your stay but enjoy your time.</p>
      </div>
      <div class="col-md-4">
        <img src="https://i.ibb.co/ZLDv3Nq/noun-selection-1214259.png" alt="Options">
        <h4>Free Listings</h4>
        <p>Offer your home to other people. You don't need to pay for listing. And can set your own price.</p>
      </div>

    </div>
  </div>

app/views/reviews/_form.html.erb
<%= simple_form_for([@flat, @review]) do |f| %>
    <%= f.input :description %>
    <%= f.input :stars %>
    <%= f.submit class: "btn btn-primary", id: "book" %>
<% end %>

app/views/reviews/index.html.erb
<body  style="background-image: linear-gradient(rgba(0,0,0,0.5),rgba(0,0,0,0.5)),  url('https://ui-ex.com/images/texas-drawing-skyline-2.png')">

  <div class="container">
    <h1>This Flat's Reviews</h1>
      <ul>
        <% @reviews.each do |b| %>
          <li>
            <%= b.description %> |
            <%= b.stars %> Stars
            <%= link_to "x", review_path(b), method: :delete, data: { confirm: 'are you sure' } %>

          </li>
        <% end %>
      </ul>
      <%= link_to 'Back', 'javascript:history.back()', class: "btn ", id: "couple" %>
      <%#= link_to "Back", flat_booking_path(@flat, @booking), class: "btn ", id: "couple"  %>
  </div>
</body>

app/views/reviews/new.html.erb
<body  style="background-image: linear-gradient(rgba(0,0,0,0.5),rgba(0,0,0,0.5)),  url('https://ui-ex.com/images/texas-drawing-skyline-2.png')">

  <div class="container">
    <h1>YOUR REVIEW</h1>

    <%= render 'form' %>
  </div>

</body>

app/views/reviews/show.html.erb
<body style="background-image: linear-gradient(rgba(0,0,0,0.5),rgba(0,0,0,0.5)),  url('https://ui-ex.com/images/texas-drawing-skyline-2.png')" >
  <div class="container">
    <h1>Your new Review</h1>
    <ul class="list-unstyled">
      <li>
        <p style="font-size: 20px;"><%= @review.description %></p>
        <p><%= @review.stars %>  <i class="fas fa-star"></i> </p>
      </li>
    </ul>
    <div class="flexbox" id="review-back-btn">
          <%= link_to "Delete Review", flat_review_path(@flat), method: :delete, data: { confirm: 'are you sure' } %>

          <%= link_to "Back", flat_path(@flat) %>
      </div>
  </div>
</body>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light" id="nav">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "https://i.ibb.co/SDkhdwm/slothquadrate.png" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Home", flats_path, class: "nav-link", id: "home-link" %>
      </li>
      <% if !user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_url, class: "nav-link", id: "login-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Profile", dashboard_path, class: "nav-link", id: "profile-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Create Flat", new_flat_path, class: "nav-link", id: "create-link" %>
        </li>
      <% end %>
      <li class="nav-item dropdown">
        <%= image_tag "https://cdn2.iconfinder.com/data/icons/scenarium-vol-4/128/011_avatar_anonymous_profile_privacy_hacker_mask_hoodie-512.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
      </li>
    </ul>
  </div>
</div>